title: My Blog
description: Blog posts for calendar events
baseurl: "/blog"
url: "https://micaelaniemi.github.io"
permalink: /posts/:year/:slug
collections:
  years:
    output: true
    permalink: /posts/:year/
