title: MN Blog
description: Micaela Niemi's Blog
username: micaelaniemi
repository: micaelaniemi/blog
url: https://micaelaniemi.github.io
baseurl: /blog
future: true
collections:
  posts:
    output: false
permalink: none
