title: MN Blog
description: Micaela Niemi's Blog
username: micaelaniemi
repository: micaelaniemi.github.io
#baseurl: "/blog"
#url: "https://micaelaniemi.github.io"
future: true
collections:
  posts:
    output: false
permalink: none
