title: MN Blog
description: Micaela Niemi's Blog
repository: micaelaniemi/micaelaniemi.github.io
username: micaelaniemi
baseurl: "/blog"
url: "https://micaelaniemi.github.io"
collections:
  posts:
    output: false
permalink: none
