title: MN Blog
description: Micaela Niemi's Blog
baseurl: "/blog"
url: "https://micaelaniemi.github.io"
permalink: none
future: true # Allow future-dated posts
exclude: [] # Prevent accidental exclusions
