name: Deploy Jekyll to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Build Jekyll
        run: bundle exec jekyll build --baseurl "/blog"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
